### ISSUE TITLE
Run-time error: `useSlate` hook must be used inside the <Slate> component's context.

### ISSUE THREAD

**Issue by alexander-kolarov-tiebreak** [we-are-you/payloadcms-slate-plugin-textcolor-leav#1]
I receive error when try to use it:

```
2885 Uncaught 
Error: The `useSlate` hook must be used inside the <Slate> component's context.
at useSlate (index.es.js:2885:11)
at LeafButton (index.js:87:50)
```

**Comment by shaneheyworth** [comment]
I receive the same error. And can replicate it with anything I try. Did you get this fixed?

**Comment by ChillerPerser** [comment]
Which Version of PayloadCMS you are using?

**Comment by shaneheyworth** [comment]
Payload 2.0

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ChillerPerser** [comment]
Made some tests with these packages and its working great.

- @payloadcms/richtext-slate 1.5.2 and 1.4.0
- slate 0.91.4

Which versions are you using exactly?
Does this happen with the PayloadCMS Website Template?

**Comment by shaneheyworth** [comment]
"@payloadcms/richtext-slate": "^1.5.2",
    "payload": "^2.0.0",
    
    I do not have slate installed as it warns that a second instance of slate unrelated to the first one
